### ISSUE TITLE
Can't login in app

### ISSUE THREAD

**Issue by djandDK** [svbnet/AthamePlugin.Tidal#1]
i get an error sadly written in danish, with no error code. but it does say "the input was either too big or too small for int32." and then the first line in the error is "convert.toint32(int64)" 

(most likely is that my mail is too long)

[error.txt](https://github.com/svbnet/AthamePlugin.Tidal/files/1137100/error.txt)

**Comment by fabriccioguzman** [comment]
Every time you update anything athame make sure you have deleted the athame folder that is in C: \ Users \ your user \ AppData \ Roaming

**Comment by Madeintyo** [comment]
Hate to be the bearer of bad news but I'm also having the same issue and I've deleted the athame folder in Roaming as well. Thanks, I really appreciate the speed in which you respond to these issues.

**Comment by fabriccioguzman** [comment]
you're welcome
But has it worked?

**Comment by Madeintyo** [comment]
Nah it didn't . Still get the same error @djandDK is talking about

**Comment by djandDK** [comment]
@fabriccioguzman  i'm almost 100% sure that it's because the mail i'm using is too long, i tried with a shorter mail and it worked.
the mail i use for my main tidal account is 29 letters long and the mail i used for my new signup is only 16, another diffrence between the 2 mails is that one has punctuation. the 29 letters long goes something like "myfirstname.mymiddlename.mylastname@hotmail.com" and the new one is "myfirstname@customdomain.dk"

**Comment by Madeintyo** [comment]
The email I'm using isn't long and has no special characters other than letters or numbers so I'm even more confused why I'm getting that error when I try to login with it.

**Comment by fabriccioguzman** [comment]
Share a catch of error please

**Comment by Madeintyo** [comment]
I get the same error, "Value was either too small for an Int32." Here's the debug.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at AthamePlugin.Tidal.InternalApi.TidalClient.DeserializeOrThrow[T](JObject result)
   at AthamePlugin.Tidal.InternalApi.TidalClient.<GetAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AthamePlugin.Tidal.InternalApi.TidalClient.<GetUserAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AthamePlugin.Tidal.TidalService.<AuthenticateAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Athame.UI.CredentialsForm.<>c__DisplayClass4_0.<<okButton_Click>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Athame
    Assembly Version: 0.4.4.0
    Win32 Version: 0.4.4
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Athame.exe
----------------------------------------
Athame.PluginAPI
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Athame.PluginAPI.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.2.20802
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 1.1.2.0
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
AthamePlugin.GooglePlayMusic
    Assembly Version: 2.0.0.0
    Win32 Version: 0.4.4
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Athame.exe
----------------------------------------
GoogleMusicApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Plugins/GooglePlayMusic/GoogleMusicApi.dll
----------------------------------------
AthamePlugin.Tidal
    Assembly Version: 2.1.0.0
    Win32 Version: 0.4.4
    CodeBase: file:///C:/Users/David/Downloads/Compressed/athame-0.4.4-base-plugins/athame-0.4.4/Athame.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nickemitchell24** [comment]
Getting the same issue as well. An interesting prespective that I have is a friend let me use his account and that worked, but when I tried my account it started throwing this error. My account was initially only linked to a Facebook login but I changed it to have a password and normal login. Don't know if that is part of the issue.

**Comment by Madeintyo** [comment]
Thanks @nickemitchell24 that little detail helped big time. I just tried an account that wasn't linked to facebook and it worked so I'm guessing that's the issue.

**Comment by nickemitchell24** [comment]
@Madeintyo I reached out to Tidal to see if they would be able to unlink the Facebook login from my account and I'll update you if that is possible. That way you don't have to change anything to work around it and people who have the issue can just contact Tidal.

**Comment by svbnet** [comment]
Fixed. See latest release for details.
